In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

X_train, X_test

(array([[-1.01232181,  0.28123049, -0.87512274, ...,  1.15469377,
          1.18259881, -1.27036205],
        [-0.02101069,  0.74744497, -0.03870931, ..., -0.10435845,
         -0.04258589,  0.45015563],
        [ 0.37607013,  0.33385997,  0.24958079, ..., -1.31221919,
         -0.68607663,  1.08176673],
        ...,
        [ 0.04091467,  0.42796263, -0.00235298, ..., -1.92277177,
         -0.17104772,  1.63925652],
        [ 0.3393792 , -0.64015446,  0.25253995, ..., -1.39922826,
         -0.52991248, -0.7348109 ],
        [ 1.84815207, -0.31305803,  1.78069642, ...,  0.60451533,
         -1.56102804, -1.25040773]], shape=(750, 10)),
 array([[ 0.74030596,  0.42548993,  0.6039124 , ..., -0.709441  ,
         -0.98264957, -1.3716737 ],
        [-1.49577819,  0.38135283, -1.2763343 , ...,  0.57404193,
          1.80201193, -0.63014283],
        [-0.14407863, -0.00928856,  0.02366179, ..., -0.34287886,
          0.65257238,  1.8134077 ],
        ...,
        [ 0.2787705 ,  0.43945269,  0

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
scaler = StandardScaler()

logreg = LogisticRegression()

In [5]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
logreg.fit(X_train_scaled, y_train)

y_pred = logreg.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(f"The Accuraccy Score is: {accuracy_score(y_test, y_pred)}")
print(f"The Confusion Matric is: \n{confusion_matrix(y_test, y_pred)}")
print(f"The Classification Reports are: \n{classification_report(y_test, y_pred)}")

The Accuraccy Score is: 0.828
The Confusion Matric is: 
[[ 98  15]
 [ 28 109]]
The Classification Reports are: 
              precision    recall  f1-score   support

           0       0.78      0.87      0.82       113
           1       0.88      0.80      0.84       137

    accuracy                           0.83       250
   macro avg       0.83      0.83      0.83       250
weighted avg       0.83      0.83      0.83       250

