In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
from sklearn.datasets import make_classification

X, y = make_classification(n_features=10, n_samples=1000, n_classes=3, n_informative=3, random_state=42)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.30)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()
logistic.fit(X_train_scaled, y_train)
y_pred = logistic.predict(X_test_scaled)

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(f"The Accuraccy Score is: {accuracy_score(y_test, y_pred)}")
print(f"The Confusion Matric is: \n{confusion_matrix(y_test, y_pred)}")
print(f"The Classification Reports are: \n{classification_report(y_test, y_pred)}")

The Accuraccy Score is: 0.7033333333333334
The Confusion Matric is: 
[[76 20  7]
 [25 48 23]
 [ 2 12 87]]
The Classification Reports are: 
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.60      0.50      0.55        96
           2       0.74      0.86      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.70      0.70      0.70       300

